config/routes.rb
AmuraBuzz::Application.routes.draw do

  get '/stream' => 'stream#index'

  get '/chat' => 'chat/private_chats#chat'
  get '/chats' => 'chat/private_chats#index'

  get '/public_chat' => 'chat/public_chats#chat'
  get '/public_chats' => 'chat/public_chats#index'

  devise_for :users,:controllers => {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  # match 'users/auth/:provider/callback' => 'omniauthcallbacks#facebook' ,via: :get  devise_for :users,:controllers => {registrations: 'registrations',:omniauth_callbacks => "users/omniauth_callbacks",:sessions => "sessions"}

  resources :users, :defaults => { :id => 'me',:user_id => 'me' } do
    member do
      get :profile
      get 'follow/:followed_id' => "relationships#follow", :as => 'follow'
      get 'unfollow/:followed_id' => "relationships#unfollow", :as => 'unfollow'
      get "friends" => "relationships#friends", :as => 'friends'
      get "followers" => "relationships#followers", :as => 'followers'
      get "following" => "relationships#following", :as => 'following'
    end

    resources :images
    resources :chats, only: [] do
      post :send_message, on: :collection
    end
    resources :activities,:only => [:index]
    resources :tweets do
      resources :votes, only: [:index,:create]
      resources :comments, only: [:index,:create]
      resources :shares, only: [:index,:create]
    end
  end

  root 'users#show'
end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Relationship < ActiveRecord::Base
  include PublicActivity::Common

	belongs_to :follower, :class_name => "User"
	belongs_to :followed, :class_name => "User"

  validates_presence_of :follower_id, :followed_id

end

app/controllers/admin/relationships_controller.rb
class Admin::RelationshipsController < Admin::ResourcesController
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :check_login
  before_action :get_user #,only: [:friends, :followers, :following]

  def friends
    @friends = current_user.friends
    @friends = @friends.map{|f| f.ui_json}

    respond_to do |format|
       format.json { render json: @friends }
    end
  end

  def followers
    @followers = @user.followers

    respond_to do |format|
      format.html { render :friends }
      format.json { render json: @followers }
      format.js
    end
  end

  def following
    @following = @user.following

    respond_to do |format|
      format.html { render :friends }
      format.json { render json: @followers }
      format.js
    end
  end

  def follow
    respond_to do |format|
      if current_user.follow(params[:followed_id])
        format.html { redirect_to :back, notice: 'User followed successfully' }
        format.json { render json: @user }
      else
        format.html { redirect_to :back }
        format.json { render json: 'Invalid operation', status: :unprocessable_entity }
      end
    end
  end

  def unfollow
    respond_to do |format|
      if current_user.unfollow(params[:followed_id])
        format.html { redirect_to :back, notice: 'User unfollowed successfully' }
        format.json { render json: @user }
      else
        format.html { redirect_to :back }
        format.json { render json: 'Invalid operation', status: :unprocessable_entity }
      end
    end
  end

	private
  def get_user
    if params[:id].blank? || params[:id] == 'me' || params[:id] == current_user.id
      @user = current_user
    else
      @user = User.find(params[:id])
    end
  end
end

app/views/relationships/friends.html.erb
<div class="user_wrapper">
	<div class="container-fluid border-shadow">
		<h3>
			<% if @followers.present? %>
				<%= @user.user_name %>'s followers
				<% @friends = @followers %>
			<% elsif @following.present? %>
				Followed by <%= @user.user_name %>
				<% @friends = @following %>
			<% end %>
			<%= link_to "Make more friends",users_path, class: "btn btn-primary btn-xs pull-right" %>
		</h3>
		<div class="row">
			<table id="followers_table" class="table table-stripped col-md-4">
				<% @friends.each do |friend| %>
					<tr>
          	<td><%= profile_pic_tag friend.profile_picture.file.url(:thumb), 'img-sm' %></td>
						<td><%= link_to friend.user_name, user_path(friend) %></td>
						<td>
							<% if current_user.following?(friend) %>
								<%= link_to "Unfollow",unfollow_user_path(friend),class: "btn btn-xs btn-warning" %>
							<% else %>
								<%= link_to "Follow",follow_user_path(friend), class: "btn btn-xs btn-success" %>
							<% end %>
						</td>
					</tr>
				<% end if @friends.present? %>
			</table>
		</div>
	</div>
</div>