config/routes.rb
AmuraBuzz::Application.routes.draw do

  get '/stream' => 'stream#index'

  get '/chat' => 'chat/private_chats#chat'
  get '/chats' => 'chat/private_chats#index'

  get '/public_chat' => 'chat/public_chats#chat'
  get '/public_chats' => 'chat/public_chats#index'

  devise_for :users,:controllers => {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  # match 'users/auth/:provider/callback' => 'omniauthcallbacks#facebook' ,via: :get  devise_for :users,:controllers => {registrations: 'registrations',:omniauth_callbacks => "users/omniauth_callbacks",:sessions => "sessions"}

  resources :users, :defaults => { :id => 'me',:user_id => 'me' } do
    member do
      get :profile
      get 'follow/:followed_id' => "relationships#follow", :as => 'follow'
      get 'unfollow/:followed_id' => "relationships#unfollow", :as => 'unfollow'
      get "friends" => "relationships#friends", :as => 'friends'
      get "followers" => "relationships#followers", :as => 'followers'
      get "following" => "relationships#following", :as => 'following'
    end

    resources :images
    resources :chats, only: [] do
      post :send_message, on: :collection
    end
    resources :activities,:only => [:index]
    resources :tweets do
      resources :votes, only: [:index,:create]
      resources :comments, only: [:index,:create]
      resources :shares, only: [:index,:create]
    end
  end

  root 'users#show'
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                :integer          not null, primary key
#  file_file_name    :string(255)
#  file_content_type :string(255)
#  file_file_size    :integer
#  file_updated_at   :datetime
#  tags              :string(255)
#  description       :string(255)
#  folder            :string(255)
#  image_type        :string(255)
#  imageable_id      :integer
#  imageable_type    :string(255)
#  active            :boolean          default(TRUE)
#  created_at        :datetime
#  updated_at        :datetime
#

class Image < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :imageable, polymorphic: true
  belongs_to :tweet

  has_attached_file :file, {
    preserve_files: "true",
    default_url: "default_user.jpg",
    path: ":rails_root/public/system/:attachment/:id/:style/:filename",
    url: "/system/:attachment/:id/:style/:filename",
    :styles => {
      thumb: "100x100#",
      small: "150x150>",
      medium: "200x200"
    }
  }

  serialize :tags

  validates :image_type, presence: true
	validates_attachment :file, attachment_presence: true, content_type: { content_type: ["image/jpeg", "image/jpg", "image/png"] }, size: { in: 0..5.megabytes }

  default_scope { where(active: true).order("updated_at DESC")}

  def ui_json
    to_json
  end

  def as_json(options={})
    json = super
    json[:file_url] = self.file_url
    json[:thumb_file_url] = self.file_url(:thumb)
    json[:small_file_url] = self.file_url(:small)
    json[:medium_file_url] = self.file_url(:medium)

    return json
  end

  def file_url(type = nil)
    self.file.url(type)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :check_login
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @folders = current_user.images.group_by{|i| i.folder}

    respond_to do |format|
      format.html{}
      format.json {render json: @folders.to_json }
    end
  end

  def create
    @image = current_user.images.build
    @image.folder = params[:folder]
    @image.image_type = params[:image_type]
    @image.tweet_id = params[:tweet_id]
    @image.file = params[:attachment].first

    respond_to do |format|
      if @image.save
        format.json { render :json => @image, status: :created }
      else
        format.json { render :json => {:errors => @image.errors.full_messages} }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.json { render json: @image, status: :updated}
      else
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @image.destroy
        format.html { redirect_to client_images_path, notice: 'Deleted successfully' }
        format.json { head :no_content }
      else
        format.html { redirect_to client_images_path, alert: 'Failed to delete' }
        format.json { head :no_content }
      end
    end
  end

  def get_images
    matcher = {}
    if params[:folder].present?
      if params[:folder] == "Documents"
        matcher["$or"] = [{folder:"Documents"},{folder: nil}]
      else
        matcher[:folder] =  params[:folder]
      end
    end

    if params[:type].present?
      matcher[:content_type] =  Regexp.new(params[:type])
    end
    if params[:term].present?
      matcher[:name] = Regexp.new(params[:term], "i")
    end
    @images = current_user.images.where(matcher)

    respond_to do |format|
      format.html {           }
      format.json {render json: @images.collect{|x| JSON.parse(x.json)}}
    end
  end

  private

  def set_image
    @image = current_user.images.find(params[:id])
  end
end

app/views/images/edit.html.erb
<%= link_to 'All Images',user_images_path('me'), class: 'btn btn-link' %>

<div class="row">
	<div class="col-md-12">

		<div class="form-group">
			<%= image_tag @image.file.url, {class: 'img-thumbnail', id:'canvas',width: '750px',height: '400px'} %>
		</div>

		<div class="form-group">
			<div class="panel panel-default">
				<div class="panel-heading text-center">
					<strong>Preset Filters</strong>
				</div>
				<div class="panel-body wrap_word" role="tabpanel">
					<%= render :partial => 'partials/caman_preset_filters' %>
				</div>
			</div>
		</div>

		<div class="form-group mt20">
			<div class="panel panel-default">
				<div class="panel-heading text-center">
					<strong>Default Filters</strong>
				</div>
				<div class="panel-body wrap_word" role="tabpanel">
					<div class="form-group">
						<%= render :partial => 'partials/caman_default_filters' %>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>

<%= javascript_tag do %>
	$(document).ready(function(){
		var c = Caman('#canvas');

		Caman.Event.listen("processStart", function (job) {
		  console.log("Start:", job.name);
		});

		Caman.Event.listen(c, "processComplete", function (job) {
		  console.log("Finished:", job.name);
		});

		$('.filter_range').change(function(){
			var val = $(this).val();
			var filter_name = $(this).data('filter');
			$(this).closest('.FilterSetting').find('.FilterValue').text(val);
			eval("c." + filter_name + "(" + val + ")");
			c.render();
		});
	});
<% end %>

app/views/images/index.html.erb
<div class="row form-group mt20">
  <div class="col-md-3">
    <span class="btn btn-primary fileinput-button">
      <i class="fa fa-plus"></i>
      <span>Add Pictures</span>
      <input class="picture-upload" type="file" name="attachment[]" data-url="/users/me/images"\>
    </span>
  </div>
  <div class="upload-details hidden">
    <div class="col-md-3 text-center">
      <span class="fileinput-files text-sm pull-left"></span>&nbsp;
    </div>
    <div class="col-md-4 text-center">
      <%= select_tag 'folder', options_for_select(@folders.collect{ |k,v| [k, k] }), prompt: 'Select Folder', class: 'form-control input-sm' %>
      <span>OR</span>
      <input placeholder='Create new folder' id="new_folder" class="form-control input-sm"\>
    </div>
    <div class="col-md-2">
      <button class="btn btn-success confirm-upload">Upload</button>
    </div>
  </div>
  <div class="progress asset-loading hidden">
    <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:0%"></div>
  </div>
</div>

<% @folders.each do |folder, images| %>
	<div class="folder mt10" data-name="<%= folder.downcase.gsub(" ","_") %>">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h4><i class="fa fa-folder-open-o"></i> <%= folder %></h4>
        <div class="galleria">
          <% images.each do |image| %>
            <%= image_tag image.file.url, class: 'img-thumbnail img-md', data: {title: "#{image.file_file_name}", description: "#{image.file_file_name}", link: "#{user_image_path('me', image)}"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<%= javascript_tag do %>
	Galleria.run('.galleria');

  Amura.init_file_uploader($(".picture-upload"), {
    data_type: 'json',
    type: 'POST',
    dropzone: $(".post-tweet-form"),
    on_add: function (e, data) {
      console.log("on_add : ", data);

      if(data.files[0].type.match(/jpg|png|jpeg/i)){
        var html = "<span>"+data.files[0].name+"</span>";
        $(".fileinput-files").html(html);
        $(".upload-details").removeClass("hidden");
        $(".confirm-upload").click(function(e){
          var folder_name = $("#new_folder").val() || $("#folder").val();
          data.formData = {
            folder: folder_name,
            image_type: 'upload'
          }
          console.log(data.formData);
          data.submit();
        });
      }else{
        $(".media-upload").empty();
        Amura.global_error_handler("Invalid file type '"+data.files[0].type+"', allowed file types are 'jpg, png, jpeg'. ");
        return false;
      }

    },

    on_start: function(e, data){
      console.log("on_start : ", data);
    },
    on_progress: function(e, data){
      var progress = parseInt(data.loaded / data.total * 100, 10);
      $(".asset-loading").find(".progress-bar").css("width", progress + "%");
    },
    on_success: function(e, data){
      console.log("on_success ; ", data.result);
      $(".upload-details").addClass("hidden");
      window.location.reload();
    },
    on_error: function(errors){
      Amura.global_error_handler(errors);
    }
  });
<% end %>

app/views/images/show.html.erb
<%= link_to 'All Images',user_images_path('me'), class: 'btn btn-link' %> |
<%= link_to 'Edit',edit_user_image_path('me', @image), class: 'btn btn-link' %>

<p>name : <%= @image.file_file_name %></p>
<p>size : <%= @image.file_file_size %></p>
<p>image_type : <%= @image.image_type %></p>
<p>folder : <%= @image.folder %></p>

<%= image_tag @image.file.url,class: 'img-thumbnail' %>